version: 2.1

jobs:
  build-lint-and-test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
            name: run linter and save it in XML
            command: |
              . venv/bin/activate
              flake8 --exclude=venv,venv_p13,oc_lettings_site/migrations,lettings/migrations,profils/migrations,docs
            when: always
      - run:
          name: run tests and save it in XML
          command: |
            . venv/bin/activate
            python manage.py test

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: artifact-file

  build-and-push-to-dockerhub:
    docker:
      - image: cimg/python:3.9.6
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and push docker image
          command: |
            docker build -t hlouppe/openproject13 .
            echo 'gtcVqtMu42?' | docker login -u herbet.hadrien@gmail.com --password-stdin docker.io
            docker push hlouppe/openproject13:latest
  deploy-docker-on-server:
      machine:
        image: ubuntu-2204:2023.07.2
      
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - "6a:ab:ad:ad:b1:ca:04:55:4d:e7:b5:6a:48:7e:03:d3"
        - run:
            name: deploy the docker image on server
            command: |
              ssh -o "StrictHostKeyChecking no" root@212.86.104.93 "./circleScript.sh"


workflows:
  main-workflow:
    jobs:
      - build-lint-and-test
      - build-and-push-to-dockerhub:
          requires:
            - build-lint-and-test
          filters:
            branches:
              only: master
      - deploy-docker-on-server:
          requires:
            - build-and-push-to-dockerhub
          filters:
            branches:
              only: master