name: CI/CD

on: [push]  # Déclenche le pipeline à chaque push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: build  # Attend que le job de build soit terminé
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy if tests passed
        if: ${{ needs.build.result == 'success' }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker/setup-buildx-action@v2
          docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: hlouppe/clockbox:latest
        env:
          DOCKERHUB_USERNAME: hlouppe
          DOCKERHUB_PASSWORD: dckr_pat_GG6IICC8cVesd7kKQtt1kB8pw34
