name: CI/CD

on: [push]  # Déclenche le pipeline à chaque push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: build  # Attend que le job de build soit terminé
    runs-on: ubuntu-latest
    steps:
      - name: Deploy if tests passed
        if: ${{ needs.build.result == 'success' }}
        run: |
          echo "Coucou"
